import { Characters } from "@/types"
import { CharacterAttributes, CharacterType } from "@prisma/client"

export const iconRatio = 30

export const characters: Characters[] = [
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ルフィ',
    label: 'ギア 5',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
];
