import { Characters } from "@/types"
import { CharacterAttributes, CharacterType } from "@prisma/client"

export const iconRatio = 30

export const characters: Characters[] = [
  {
    name: 'シャンクス',
    label: 'FILM RED',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ルフィ',
    label: 'ギア 5',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ルフィ太郎',
    label: 'ワノ国',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ホネ吉',
    label: 'ワノ国',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '四皇',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ナイトメア・ルフィ',
    label: '希望の星',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ルフィ',
    label: 'ギア4／バウンドマン',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'アルベル',
    label: 'ルナーリア族',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ヤマト',
    label: '大口真神',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ルフィ',
    label: 'ギア4／スネイクマン',
    attributes: CharacterAttributes.RED,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シルバーズ・レイリー',
    label: 'ロジャー海賊団／副船長',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'エドワード・ニューゲート',
    label: 'ロジャーの好敵手',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シルバーズ・レイリー',
    label: '海賊王の右腕 冥王',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: '2年後／船長',
    label: 'モンキー・D・ルフィ',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'キッド&ロー',
    label: '鬼ヶ島怪物決戦',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ヤマト',
    label: 'カイドウの息子',
    attributes: CharacterAttributes.RED,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'トラファルガー・ロー',
    label: '死の外科医',
    attributes: CharacterAttributes.RED,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'サボ',
    label: 'ルフィの兄',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ジュラキュール・ミホーク',
    label: '世界最強の剣士',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'カイドウ',
    label: '百獣海賊団／総督',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ウタ',
    label: '新時代の歌い手',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ユースタス・キッド',
    label: '鬼ヶ島討ち入り',
    attributes: CharacterAttributes.RED,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ドンキホーテ・ドフラミンゴ',
    label: 'ドンキホーテ海賊団／船長',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'クイーン',
    label: '百獣海賊団／大看板',
    attributes: CharacterAttributes.RED,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ベン・ベックマン',
    label: 'FILM RED',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ニコ・ロビン',
    label: '鬼ヶ島討ち入り',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ロロノア・ゾロ',
    label: '2年後／戦闘員',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ブルック',
    label: '鬼ヶ島討ち入り',
    attributes: CharacterAttributes.RED,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'うるティ',
    label: '百獣海賊団／飛び六砲',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'X・ドレーク',
    label: '機密特殊部隊「SWORD」隊長',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'バギー',
    label: '王下七武海',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ゲッコー・モリア',
    label: '頂上戦争',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'スクラッチメン・アプー',
    label: 'オンエア海賊団／船長',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ヒナ',
    label: '海軍本部／少将',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ゾロ十郎',
    label: 'ワノ国',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'トラファルガー・ロー',
    label: 'ハートの海賊団／船長',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'マルコ',
    label: '白ひげ海賊団／一番隊隊長',
    attributes: CharacterAttributes.RED,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'フラの介',
    label: 'ワノ国',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'トニートニー・チョッパー',
    label: '2年後／船医',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ペル',
    label: 'アラバスタ王国護衛隊副官',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ページワン',
    label: '百獣海賊団／飛び六砲',
    attributes: CharacterAttributes.RED,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ルフィ',
    label: '頂上戦争',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'X・ドレーク',
    label: 'ワノ国',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ジャック',
    label: '百獣海賊団／大看板',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'コラソン',
    label: 'ドンキホーテファミリー／幹部',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'トニートニー・チョッパー',
    label: '腕力強化',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ゴール・D・ロジャー',
    label: '海賊王',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: '【サカズキ】',
    label: '海軍本部／元帥　赤犬',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ウタ',
    label: 'FILM RED',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ルフィ',
    label: 'ルフィ・ロー海賊同盟',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'カイドウ',
    label: '最強生物',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ポートガス・D・エース',
    label: '火拳',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ルフィ',
    label: 'FILM RED',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: '光月おでん',
    label: '九里大名',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'カイドウ',
    label: '鬼ヶ島怪物決戦',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ルフィ',
    label: '海賊王を夢見る男',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'バギー',
    label: 'バギー海賊団／船長',
    attributes: CharacterAttributes.RED,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'マルコ',
    label: 'ワノ国',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ウソップ',
    label: '5tハンマー',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ルフィ',
    label: 'STAMPEDE',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ルフィ',
    label: '鬼ヶ島討ち入り',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ボア・ハンコック',
    label: '九蛇海賊団／船長',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'コビー',
    label: '海軍本部／曹長',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モネ',
    label: 'ドンキホーテ海賊団／幹部',
    attributes: CharacterAttributes.RED,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ミス・ウェンズデー',
    label: 'BW／フロンティアエージェント',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ゲッコー・モリア',
    label: '王下七武海',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'トラファルガー・ロー',
    label: '鬼ヶ島討ち入り',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'バジル・ホーキンス',
    label: 'ワノ国',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シリュウ',
    label: '黒ひげ海賊団／元インペルダウン看守長',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'サンジ',
    label: '2年後／コック',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ナミ',
    label: '天候棒',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ユースタス・キッド',
    label: '新世界',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ボア・ハンコック',
    label: '王下七武海',
    attributes: CharacterAttributes.RED,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'そげキング',
    label: '狙撃の王様',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'バーソロミュー・くま',
    label: '王下七武海',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ルフィ',
    label: 'ゴムゴムの暴風雨',
    attributes: CharacterAttributes.RED,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ウルージ',
    label: '破戒僧海賊団／船長 "怪僧"',
    attributes: CharacterAttributes.RED,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'クロコダイル',
    label: '王下七武海',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'カク',
    label: 'CP9',
    attributes: CharacterAttributes.RED,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ニコ・ロビン',
    label: '麦わらの一味／考古学者',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ブルック',
    label: '麦わらの一味／音楽家',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'クザン',
    label: '元海軍本部大将',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'おそばマスク',
    label: 'ステルス・ブラック',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'エンポリオ・イワンコフ',
    label: '革命軍',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'アルビダ',
    label: 'アルビダ海賊団／船長',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'トニートニー・チョッパー',
    label: '麦わらの一味／船医',
    attributes: CharacterAttributes.RED,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ガープ',
    label: '海軍の英雄',
    attributes: CharacterAttributes.RED,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'カラス',
    label: '革命軍／"北軍"軍隊長',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ヘルメッポ',
    label: '七光り',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ルフィ',
    label: '3000万の賞金首',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャーロット・カタクリ',
    label: 'ビッグ・マム海賊団／スイート3将星',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'キラー',
    label: '鬼ヶ島討ち入り',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'クイーン',
    label: '絡繰人間',
    attributes: CharacterAttributes.RED,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ビスタ',
    label: '白ひげ海賊団／5番隊隊長',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'チュウ',
    label: 'アーロン一味／幹部',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'たしぎ',
    label: '海軍本部／曹長',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'モンキー・D・ルフィ',
    label: '麦わらの一味／船長',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'フランキー将軍',
    label: '鉄の海賊',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'はっちゃん',
    label: 'アーロン一味／幹部',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ドン・クリーク',
    label: 'クリーク海賊団／船長',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ゼフ',
    label: 'バラティエ／料理長',
    attributes: CharacterAttributes.RED,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'キャプテン・クロ',
    label: 'クロネコ海賊団／元船長',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ロブ・ルッチ',
    label: 'CP0',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ギン',
    label: 'クリーク海賊団／戦闘総隊長',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: '【クザン】',
    label: '海軍本部／大将 青雉',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'イゾウ',
    label: '元白ひげ海賊団／16番隊隊長',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: '【ボルサリーノ】',
    label: '海軍本部／大将 黄猿',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ロロノア・ゾロ',
    label: '一大・三千・大千・世界',
    attributes: CharacterAttributes.RED,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ヴィンスモーク・ジャッジ',
    label: 'ジェルマ66／総帥',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'トレーボル',
    label: 'ドンキホーテ海賊団／最高幹部',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'クロコダイル',
    label: '頂上戦争',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ナミ',
    label: 'ホールケーキアイランド',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'クンフージュゴン',
    label: '武闘派アニマル',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ジンベエ',
    label: '王下七武海',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ジーザス・バージェス',
    label: '黒ひげ海賊団／操舵手 "チャンピオン"',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '赤髪海賊団／大頭',
    attributes: CharacterAttributes.RED,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ネコマムシ',
    label: '夜の王',
    attributes: CharacterAttributes.RED,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: '菊之丞',
    label: 'ワノ国一の美少年剣士',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'キャロット',
    label: 'ミンク族',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'トニートニー・チョッパー',
    label: 'ハッピーホリデー',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'バルトロメオ',
    label: 'バルトクラブ／船長',
    attributes: CharacterAttributes.RED,
    type: CharacterType.DEFENDER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ロブ・ルッチ',
    label: 'CP9',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'エネル',
    label: '神',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ウソップ',
    label: '2年後／狙撃手',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ミス・オールサンデー',
    label: 'BW／副社長',
    attributes: CharacterAttributes.BLUE,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'ペローナ',
    label: 'スリラーバーク海賊団／四怪人',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.GETTER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
  {
    name: 'シャンクス',
    label: '',
    attributes: CharacterAttributes.GREEN,
    type: CharacterType.ATTACKER,
    totalScore: 0,
    boost: 0,
  },
];
