'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { RecoilRoot } from 'recoil'

import 'ress/ress.css'
import '@/app/styles/globals.css'
import '@/utils/index'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <RecoilRoot>
      <html lang="ja">
        <body className={inter.className}>{children}</body>
      </html>
    </RecoilRoot>
  );
}
