import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import RootTemplate from './template'

import 'ress/dist/ress.min.css'
import '@/app/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <RootTemplate>{children}</RootTemplate>
      </body>
    </html>
  );
}
